version: "2"

# plugins:
#   eslint:
#     enabled: true
#     channel: "eslint-5"
#     config:
#       config: .eslintrc.js

exclude_patterns:
  - ".github/"
  - "scripts/"
  - "CHANGELOG.md"
  - "**/dist/"
  - "**/node_modules/"
  - "**/tests/"
  - "**/__fixtures__/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "**/*.spec.ts"
  - "**/*.integ.ts"
