
version: "2"

exclude_patterns:
  - ".github/"
  - "scripts/"
  - "CHANGELOG.md"
  - "**/dist/"
  - "**/node_modules/"
  - "**/tests/"
  - "**/__fixtures__/"
  - "**/vendor/"
  - "**/*.d.ts"
  - "**/*.spec.ts"
  - "**/*.integ.ts"
