name: codecov

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}} #required
    
    - name: init
      run:  |
        bash init.sh
        npm i
      env:
        CI: true
    
    - name: npm test
      run:
        npx jest --coverage
      env:
        CI: true
