name: codecov

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1

    - name: init
      run:  |
        bash init.sh
        npm i
      env:
        CI: true
    
    - name: npm test
    - uses: codecov/codecov-action@v1.0.2
      with:
        token: ${{secrets.CODECOV_TOKEN}}
      run:
        npx jest --coverage && npx codecov
      env:
        CI: true
