name: optimization

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Optimization
        run: |
          npm i
          npm run tryScript optimization

      # カバレッジのデプロイ
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.3
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      # リリース処理
      - name: Semantic release
        # branch が master の時に発火
        if: contains(github.ref, 'master')
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      # 実行結果の発火
      - name: Slack Notification
        if: always()
        uses: 8398a7/action-slack@v2
        with:
          status: ${{ job.status }}
          author_name: Slack Notification
          channel: "#github"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
