name: optimization

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [10.x, 12.x]

    steps:
      - uses: actions/checkout@v1
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: npm optimization
        run: |
          npm i
          npm run tryScript optimization

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1.0.2
        with:
          token: ${{secrets.CODECOV_TOKEN}}

      - name: Deployed
        run: npx ts-node scripts/slack
        env:
          SLACK_TOKEN: ${{secrets.SLACK_TOKEN}}
          TEXT: 'Done'
          CHANNEL: '#github'
